matrix:
  include:
    - language: objective-c
      osx_image: xcode9.4
      cache: cocoapods
      podfile: ios/werewolf-assistant/Podfile
      script:
        - xcodebuild clean build -workspace ios/werewolf-assistant/werewolf-assistant.xcworkspace -scheme werewolf-assistant -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -quiet

    - language: go
      go: "1.10.x"
      install: export GOPATH=$HOME/gopath/src/github.com/lx223/werewolf-assistant/go
      script: 
        - go test $(go list ./... | grep -v /vendor/ | grep -v /pkg/)