language: objective-c
osx_image: xcode9.4
cache: cocoapods
script:
  - xcodebuild clean build -workspace ios/werewolf-assistant/werewolf-assistant.xcworkspace -scheme werewolf-assistant -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO