matrix:
  include:
    - language: objective-c
      osx_image: xcode9.4
      script:
        - xcodebuild clean build -workspace ios/werewolf-assistant/werewolf-assistant.xcworkspace -scheme werewolf-assistant -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -quiet

    - language: go
      go: "1.10.x"
      cache:
        directories:
          - "$HOME/google-cloud-sdk/"
      install: export GOPATH=$HOME/gopath/src/github.com/lx223/werewolf-assistant/go
      script: 
        - go test $(go list ./... | grep -v /vendor/ | grep -v /pkg/)
      before_deploy:
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud --quiet version
        - gcloud --quiet components update
      deploy:
        - provider: script
          script:
            - ./scripts/publish_server.sh
          on:
            branch: server-cd