apiVersion: v1
kind: Service
metadata:
  name: grpc-werewolf
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: grpc-werewolf
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-werewolf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-werewolf
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-P", "9000",
          "-a", "grpc://127.0.0.1:21806",
          "-s", "werewolf.endpoints.trial-194900.cloud.goog",
          "--rollout_strategy", "managed",
        ]
        ports:
          - containerPort: 9000
      - name: grpc-werewolf
        image: gcr.io/trial-194900/go-werewolf:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 21806
