# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'werewolf-assistant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for werewolf-assistant
  pod 'SwiftProtobuf',                  '~> 1.0.3'
  pod 'SwiftGRPC',                      '~> 0.4.3'
  pod 'RxSwift',                        '~> 4.2.0'
  pod 'RxCocoa',                        '~> 4.2.0'
  pod 'SwiftySound',                    '~> 1.0.0'
  pod 'MaterialComponents/Snackbar',    '~> 62.0.0'
  pod 'MaterialComponents/Buttons',     '~> 62.0.0'
  pod 'R.swift',                        '~> 4.0.0'
  pod 'Floaty',                         '~> 4.0.1'

  target 'werewolf-assistantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'werewolf-assistantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
